### ISSUE TITLE
Add VPS instance as an upstream in production

### ISSUE THREAD

**Issue by guillett** [sgmap/mes-aides-ops#16]

**Comment by MattiSG** [comment]
Peut-être pas une si bonne idée : comme vu IRL, une condition serait la [_session affinity_](http://www.theserverside.com/news/thread.tss?thread_id=23914), puisque le calcul se base sur une session enregistrée sur le serveur.

Si cela n'est pas implémenté par défaut (ou activable en un flag sur Nginx), autant basculer à chaud avec un monitoring en place.

**Comment by guillett** [comment]
Le flux de production a été redirigé vers le VPS de façon transparente (cf. https://github.com/sgmap/mes-aides-ops/issues/23#issuecomment-298685203) sans incident.
