### ISSUE TITLE
Include SSL certificate issuance in CI

### ISSUE THREAD

**Issue by guillett** [sgmap/mes-aides-ops#18]
That may be overkill but should be discussed.

**Comment by MattiSG** [comment]
You mean the issuance or the test should be in CI?

**Comment by guillett** [comment]
I wanted to add the SSL issuance in CircleCI runs and the HTTPS endpoint test but it requires:

- [ ] Either use CircleCI host name (if any) or have a DNS name dynamically linked to the host IP from one of our domains. (to get a `fully.qualified.hostname`)
- [ ] To have a port forward from the CircleCI host to the build container (just like the port provided for SSH debug). (to get a `port` and be able to request a certificate for `fully.qualified.hostname:port`.
- [ ] Update the puppet script to rely on a dynamically defined hostname.

**Comment by guillett** [comment]
Too complicated. Does not worth it.
