### ISSUE TITLE
Supporter le déploiement d'une branche spécifique

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ops#25]
En tant que développeur,
Je peux lancer un déploiement en spécifiant une branche spécifique à déployer,
Pour tester une fonctionnalité ou faire un rollback.

**Comment by guillett** [comment]
## Nouvelle instance

Cela est déjà possible en suivant les indications https://github.com/sgmap/mes-aides-ops#initial-provisioning

## Instance existante

Le déploiement d'une branche spécifique se fait avec le script suivant :
```shell
UI_TARGET_REVISION=origin/staging
echo $UI_TARGET_REVISION > /opt/mes-aides/ui_target_revision
/opt/mes-aides/update.sh deploy
```

Je rajoute ça au README ?

**Comment by MattiSG** [comment]
Oui, ajouter au README et fermer cette issue.
